# Generated by Django 3.0 on 2019-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='static/img/lesson.jpg', upload_to='uploads/'),
        ),
    ]
