# Generated by Django 3.0 on 2019-12-20 15:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=600, null=True),
        ),
    ]
