# Generated by Django 3.0 on 2019-12-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='published',
            new_name='public',
        ),
    ]
