# Generated by Django 3.0.3 on 2020-03-10 06:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('lessons', '0010_auto_20200215_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('short_description', wagtail.core.fields.RichTextField()),
                ('image', models.ImageField(default='static/img/lesson.jpg', upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', wagtail.core.fields.RichTextField()),
                ('order', models.IntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(through='lessons.LessonGroup', to='lessons.Lesson'),
        ),
    ]
