# Generated by Django 3.0 on 2020-01-02 07:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20200102_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=600),
        ),
    ]
