# Generated by Django 3.0 on 2020-01-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20200102_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
