# Generated by Django 3.0.3 on 2020-03-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pro_lesson',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
