# Generated by Django 3.0.3 on 2020-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_lesson_pro_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pro_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=16, null=True),
        ),
    ]
