# Generated by Django 3.0 on 2020-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20200102_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
