# Generated by Django 3.0.3 on 2020-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20200313_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
