# Generated by Django 3.0 on 2020-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
