# Generated by Django 3.0.3 on 2020-03-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_auto_20200318_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='related_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_lessons', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_groups', to='lessons.Course'),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_groups', to='lessons.Lesson'),
        ),
    ]
