# Generated by Django 3.0.3 on 2020-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_auto_20200325_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='related_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='_lesson_related_lessons_+', to='lessons.Lesson'),
        ),
    ]
