# Generated by Django 3.0.3 on 2020-03-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_auto_20200325_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, related_name='_lesson_related_lessons_+', to='lessons.Lesson'),
        ),
    ]
