# Generated by Django 3.0.6 on 2020-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_auto_20200523_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
