# Generated by Django 3.0.6 on 2020-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_auto_20200527_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount_enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
